dataloader:
  train_ratio: 0.8
  batch_size: 128
  num_workers: 4
train:
  seed: 42
  n_epoch: 100
  gen_lr: 0.0001
  dis_lr: 0.0001
model:
  generator:
    noise_dim: 100
    label_dim: 10
    img_channels: 1
    feature_g: 64
    dropout_p: 0.5
  discriminator:
    img_channels: 1
    label_dim: 10
    feature_d: 64
    dropout_p: 0.5